---
dist: bionic
language: python
services:
- docker
install:
- pip3 install docker==4.2.2 molecule ansible-lint yamllint flake8 openshift jmespath
- ansible-galaxy collection install -r requirements.yml
script:
- OPERATORDIR="$(pwd)"
- make kustomize
- '[ -f ./bin/kustomize ] && KUSTOMIZE="$(realpath ./bin/kustomize)" || KUSTOMIZE="$(which kustomize)"'
- KUSTOMIZE_PATH=${KUSTOMIZE} TEST_OPERATOR_NAMESPACE=default molecule test -s kind
deploy:
  provider: script
  script: hack/operate.sh --push-images --verbose
  on:
    branch: master
