---
dist: bionic
language: python
services:
  - docker
install:
  - pip3 install docker==4.2.2 molecule ansible-lint yamllint flake8 openshift jmespath
  - ansible-galaxy collection install -r requirements.yml
env:
  - OPERATOR_SDK_VERSION=0.19.2
script:
  - molecule test -s test-local
deploy:
  provider: script
  script: ./build.sh -b quay -l -t $OPERATOR_SDK_VERSION -o -- --build-arg=OPERATOR_SDK_VERSION=$OPERATOR_SDK_VERSION
  on:
    branch: master
