---
dist: bionic
language: python
services:
- docker
install:
- pip3 install docker==4.2.2 molecule ansible-lint yamllint flake8 openshift jmespath
- ansible-galaxy collection install -r requirements.yml
- curl -Lo $HOME/.local/bin/kind https://kind.sigs.k8s.io/dl/v0.8.1/kind-linux-amd64
- chmod +x $HOME/.local/bin/kind
script:
- OPERATORDIR="$(pwd)"
- make kustomize
- '[ -f ./bin/kustomize ] && KUSTOMIZE="$(realpath ./bin/kustomize)" || KUSTOMIZE="$(which kustomize)"'
- KUSTOMIZE_PATH=${KUSTOMIZE} TEST_OPERATOR_NAMESPACE=default molecule test -s kind
deploy:
  provider: script
  script: hack/operate.sh --push-images --verbose
  on:
    branch: master
