---
dist: bionic
language: python
services:
  - docker
install:
  - pip3 install docker molecule ansible-lint yamllint flake8 openshift jmespath
env:
  - OPERATOR_SDK_VERSION=0.19.2
script:
  - molecule test -s test-local
  - ./build.sh -b local -d -l -t $OPERATOR_SDK_VERSION -o -- --build-arg=OPERATOR_SDK_VERSION=$OPERATOR_SDK_VERSION
deploy:
  provider: script
  script: ./build.sh -b quay -d -l -t $OPERATOR_SDK_VERSION -o -- --build-arg=OPERATOR_SDK_VERSION=$OPERATOR_SDK_VERSION
  on:
    branch: master
