= Sonarqube Operator

== Overview

This repository contains the code to build a Sonarqube Operator for Red Hat OpenShift Container Platform. It will not run on Kubernetes because it uses the `Route` object to provide access to Sonarqube.

The Operator will create a *PostgreSQL* database with persistent storage and a *SonarQube* instance also with persistent storage connected to the PostgreSQL database.

It is implemented on top of the Red Hat https://github.com/operator-framework/operator-sdk[Operator SDK] - in particular the https://github.com/operator-framework/operator-sdk/blob/master/doc/ansible/user-guide.md[Ansible Operator].

== Building the Operator

There is a script `hack/operate.sh` which will download the prerequisites (operator-sdk etc), build the operator artifacts from operator-sdk defaults, package and push the operator container image, deploy the artifacts to a Kubernetes cluster, and create a `kind: Sonarqube` CR to deploy an instance. You should use the help page to look at what the various options do, but for the most part if you want to deploy to a cluster directly from this repo you could run `hack/operate.sh -d`.

Before running the script make sure to update the location of the container image to a repository you have access to. If you decide to build your own container image for the operator, make sure to update `hack/operate.conf` with an updated container image location and add the `-p` flag to `operate.sh`.

== Installation

=== Common Installation Steps

The installation of the Custom Resource Definition and Cluster Role requires *cluster-admin* privileges. After that regular users with `admin` privileges on their projects (which is automatically granted to the user who creates a project) can provision the SonarQube Operator in their projects and deploy instances of Sonarqube using the sonarqube.gpte.opentlc.com Custom Resource.

Perform the following tasks as *cluster-admin*:

. Deploy the CustomResourceDefinition, ClusterRole, ClusterRoleBinding, ServiceAccount, and Operator Deployment:
+
[source,sh]
----
hack/operate.sh
----

. Once the Operator pod is running the Operator is ready to start creating SonarQube Servers.

. To deploy the above, and also the `config/samples/redhatgov_v1alpha1_sonarqube.yaml` example CustomResource:
+
[source,sh]
----
hack/operate.sh -d
----

== Deploying a SonarQube instance using the Operator

A SonarQube instance is deployed by creating a Custom Resource based on the sonarqube Custom Resource Definition.

.Example
+
[source,texinfo]
----
apiVersion: redhatgov.io/v1alpha1
kind: Sonarqube
metadata:
  name: sonarqube-example
spec:
  postgresql:
    volumeSize: 1Gi
    image:
      src: registry.redhat.io/rhel8/postgresql-10
      tag: latest
  sonarqube:
    ssl: true
    route: special-sonarqube-route.apps.cluster.example.com
    image:
      src: quay.io/redhatgov/sonarqube
      tag: latest
      pullPolicy: IfNotPresent
    volumeSize: 1Gi
    resources:
      memory:
        request: 2Gi
        limit: 3Gi
      cpu:
        request: 1
        limit: 2

----

. Write the definition to a file (e.g. sonarqube.yaml) and then create the SonarQube instance:
+
[source,sh]
----
oc create -f ./sonarqube.yaml
----

. The operator will first create the PostgreSQL database, wait until it is up and running and then create the SonarQube pod.
. Validate that both pods (postgresql and sonarqube) are running before proceeding.
. You can validate the existence of your SonarQube instance by querying for sonarqube objects:
+
[source,sh]
----
oc get sonarqube
----

. Get the Route for SonarQube (the PostgreSQL database is not accessible outside of the project):
+
[source,sh]
----
oc get route
----

. Use the hostname returned in your Web Browser to open the SonarQube UI (default User ID is `admin` with password `admin`).

== Deleting a SonarQube instance

Deleting a SonarQube instance and its associated resources is as simple as deleting the sonarqube object. If you created a SonarQube server called `sonarqube-example` as in the example above it suffices to run the delete command on that resource:

[source,sh]
----
oc delete sonarqube sonarqube-example
----

The Operator adds ownerReference fields to all created objects - which means that deleting the sonarqube object also deletes all objects that have been created by the Operator.

== Uninstalling the SonarQube Operator

In case you wish to uninstall the SonarQube Operator make sure that there are no more SonarQube instances running. Once all SonarQube instances have been deleted simply delete the project the operator is running in.

[source,sh]
----
oc delete project sonarqube
----

Then as *cluster-admin* delete the resources:

[source,sh]
----
hack/operate.sh -r
----
