---
- name: Create the redhatgov.io/v1alpha1.Sonarqube
  k8s:
    state: present
    namespace: '{{ namespace }}'
    definition: "{{ lookup('template', '/'.join([samples_dir, cr_file])) | from_yaml }}"
    wait: yes
    wait_timeout: 600
    wait_condition:
      type: Running
      reason: Successful
      status: "True"
  vars:
    cr_file: 'redhatgov_v1alpha1_sonarqube_molecule.yaml'

- name: Wait for Sonarqube Ingress to answer
  uri:
    url: http://localhost:30080
  register: _result
  until: _result.status == 200
  retries: 60
  delay: 5

# TODO:
#   - Validate SonarQube can be used

# - name: Add assertions here
#   assert:
#     that: false
#     fail_msg: FIXME Add real assertions for your operator
