apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: sonarqubes.gpte.opentlc.com
spec:
  group: gpte.opentlc.com
  names:
    kind: Sonarqube
    listKind: SonarqubeList
    plural: sonarqubes
    singular: sonarqube
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      type: object
      x-kubernetes-preserve-unknown-fields: true
  versions:
  - name: v1alpha1
    served: true
    storage: true
