kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: sonarqube-operator
subjects:
- kind: ServiceAccount
  name: sonarqube-operator
  # Replace this with the namespace the operator is deployed in.
  namespace: REPLACE_ME
roleRef:
  kind: Role
  name: sonarqube-operator
  apiGroup: rbac.authorization.k8s.io
