apiVersion: redhatgov.io/v1alpha1
kind: Sonarqube
metadata:
  name: sonarqube-sample
spec:
  postgresql:
    image:
      src: postgres
      tag: '10'
  sonarqube:
    expose:
      ssl: false
      kind: Ingress
      uri: localhost
  persistent: false
