---
- name: Prepare
  hosts: localhost
  connection: local
  gather_facts: false
  no_log: "{{ molecule_no_log }}"
  collections:
  - community.kubernetes

  vars:
    deploy_dir: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}/deploy"

  tasks:
  - name: Create Custom Resource Definition
    k8s:
      definition: "{{ lookup('file', '/'.join([deploy_dir, 'crds/redhatgov.io_sonarqubes_crd.yaml'])) }}"

  - name: Create namespace
    k8s:
      api_version: v1
      kind: Namespace
      name: '{{ namespace }}'

  - name: Create RBAC resources
    k8s:
      definition: "{{ lookup('template', '/'.join([deploy_dir, item]))|regex_replace('REPLACE_ME', namespace) }}"
      namespace: '{{ namespace }}'
    loop:
    - cluster_role.yaml
    - cluster_role_binding.yaml
    - service_account.yaml
