---
# This is an example playbook to execute Ansible tests.
- name: Verify
  hosts: localhost
  connection: local
  gather_facts: no
  collections:
  - community.kubernetes

  vars:
    custom_resource: |
      {{ lookup('template', '/'.join([deploy_dir, 'crds/redhatgov.io_v1alpha1_sonarqube_cr.yaml'])) }}

  tasks:
  - block:
    - name: Create the redhatgov.io/v1alpha1.Sonarqube and wait for reconciliation to complete
      k8s:
        state: present
        namespace: '{{ namespace }}'
        definition: '{{ custom_resource | from_yaml | combine(cr_adjustments) }}'
        wait: yes
        wait_timeout: 300
        wait_condition:
          type: Running
          reason: Successful
          status: "True"
      vars:
        cr_adjustments:
          spec:
            postgresql_image: postgres
            postgresql_image_tag: '10'

    rescue:
    - name: Collect logs for operator pod
      k8s_log:
        api_version: v1
        kind: Pod
        namespace: '{{ namespace }}'
        label_selectors:
        - name=sonarqube-operator
      register: log

    - name: Output operator pod logs
      debug:
        var: log

  - name: Get Pods
    k8s_info:
      api_version: v1
      kind: Pod
      namespace: '{{ namespace }}'
    register: pods

  - name: Example assertion
    assert:
      that: (pods | length) > 0
