---
# Persistent Sonarqube deployment playbook.
#
# The Playbook expects the following variables to be set in the CR:
# (Note that Camel case gets converted by the ansible-operator to Snake case)
# - PostgresqlVolumeSize
# - SonarqubeVolumeSize
# - SonarqubeSsl
# The following variables come from the ansible-operator
# - ansible_operator_meta.namespace
# - ansible_operator_meta.name (from the name of the CR)

- hosts: localhost
  gather_facts: no
  tasks:
  - name: Set up PostgreSQL
    include_role:
      name: ./roles/postgresql-ocp
    vars:
      _postgresql_namespace: "{{ ansible_operator_meta.namespace }}"
      _postgresql_name: "postgresql-{{ ansible_operator_meta.name }}"
      _postgresql_database_name: sonardb
      _postgresql_user: sonar
      _postgresql_password: sonar
      _postgresql_volume_size: "{{ postgresql.volumeSize | default(omit) }}"
      _postgresql_image: "{{ postgresql.image.src | default(omit) }}"
      _postgresql_image_tag: "{{ postgresql.image.tag | default(omit) }}"

  - name: Set up Sonarqube
    include_role:
      name: ./roles/sonarqube-ocp
    vars:
      _sonarqube_namespace: "{{ ansible_operator_meta.namespace }}"
      _sonarqube_name: "{{ sonarqube_service_name | d( ansible_operator_meta.name) }}"
      _sonarqube_ssl: "{{ sonarqube.ssl | default(omit) }}"
      _sonarqube_route: "{{ sonarqube.route | default(omit) }}"
      _sonarqube_image: "{{ sonarqube.image.src | default(omit) }}"
      _sonarqube_image_tag: "{{ sonarqube.image.tag | default(omit) }}"
      _sonarqube_image_pull_policy: "{{ sonarqube.image.pullPolicy | default(omit) }}"
      _sonarqube_volume_size: "{{ sonarqube.volumeSize | default(omit) }}"
      _sonarqube_postgresql_service_name: "postgresql-{{ ansible_operator_meta.name }}"
      _sonarqube_postgresql_database_name: sonardb
      _sonarqube_postgresql_user: sonar
      _sonarqube_postgresql_password: sonar
      _sonarqube_memory_request: "{{ sonarqube.resources.memory.request | default(omit) }}"
      _sonarqube_memory_limit: "{{ sonarqube.resources.memory.limit | default(omit) }}"
      _sonarqube_cpu_request: "{{ sonarqube.resources.cpu.request | default(omit) }}"
      _sonarqube_cpu_limit: "{{ sonarqube.resources.cpu.limit | default(omit) }}"
